{
    "type": "bundle",
    "id": "bundle--b5b5a345-3196-4c5a-92b4-3c76d93a7ccb",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c61b296e-b3d5-4b51-8423-07db935a559c",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-02-22T00:16:02.083068Z",
            "modified": "2024-02-22T00:16:02.083068Z",
            "name": "CVE-2024-26130",
            "description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-26130"
                }
            ]
        }
    ]
}