{
    "type": "bundle",
    "id": "bundle--04981f5d-5e9f-4249-b571-0d59876d59b8",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--fdf9098f-d111-4404-972f-e96b16ceacbe",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-04T01:52:26.935459Z",
            "modified": "2025-04-04T01:52:26.935459Z",
            "name": "CVE-2025-32049",
            "description": "A flaw was found in libsoup. The SoupWebsocketConnection may accept a large WebSocket message, which may cause libsoup to allocate memory and lead to a denial of service (DoS).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32049"
                }
            ]
        }
    ]
}