{
    "type": "bundle",
    "id": "bundle--681c03de-dba2-4bec-828e-76bdce38423f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--d0fa9ccf-010f-4f9c-9c0c-bb2ebc2b1643",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-10-22T01:45:26.081055Z",
            "modified": "2024-10-22T01:45:26.081055Z",
            "name": "CVE-2024-47727",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nx86/tdx: Fix \"in-kernel MMIO\" check\n\nTDX only supports kernel-initiated MMIO operations. The handle_mmio()\nfunction checks if the #VE exception occurred in the kernel and rejects\nthe operation if it did not.\n\nHowever, userspace can deceive the kernel into performing MMIO on its\nbehalf. For example, if userspace can point a syscall to an MMIO address,\nsyscall does get_user() or put_user() on it, triggering MMIO #VE. The\nkernel will treat the #VE as in-kernel MMIO.\n\nEnsure that the target MMIO address is within the kernel before decoding\ninstruction.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-47727"
                }
            ]
        }
    ]
}