{
    "type": "bundle",
    "id": "bundle--c681fcf2-b01a-4563-8027-89c5b281c544",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--f7053796-0459-4a4c-ab97-38461d181151",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-11-26T01:50:43.001536Z",
            "modified": "2024-11-26T01:50:43.001536Z",
            "name": "CVE-2020-11311",
            "description": "This record is rejected as duplicate. All references should point to CVE-2021-1904.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-11311"
                }
            ]
        }
    ]
}