{
    "type": "bundle",
    "id": "bundle--5732361d-1d3d-4b5e-8031-6f3f7f45fc31",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--165bf617-c117-4879-a6e2-64601f601d1a",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-01-29T01:41:57.463627Z",
            "modified": "2025-01-29T01:41:57.463627Z",
            "name": "CVE-2025-24478",
            "description": "A denial-of-service vulnerability exists in the affected products. The vulnerability could allow a remote, non-privileged user to send malicious requests resulting in a major nonrecoverable fault causing a denial-of-service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-24478"
                }
            ]
        }
    ]
}