{
    "type": "bundle",
    "id": "bundle--dc28e11d-9a79-40cb-ae93-906d6e4158bb",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--378ef315-bc0c-4dbb-ac5f-e9c5984e7f07",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-05-23T00:16:45.162749Z",
            "modified": "2024-05-23T00:16:45.162749Z",
            "name": "CVE-2021-47444",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\ndrm/edid: In connector_bad_edid() cap num_of_ext by num_blocks read\n\nIn commit e11f5bd8228f (\"drm: Add support for DP 1.4 Compliance edid\ncorruption test\") the function connector_bad_edid() started assuming\nthat the memory for the EDID passed to it was big enough to hold\n`edid[0x7e] + 1` blocks of data (1 extra for the base block). It\ncompletely ignored the fact that the function was passed `num_blocks`\nwhich indicated how much memory had been allocated for the EDID.\n\nLet's fix this by adding a bounds check.\n\nThis is important for handling the case where there's an error in the\nfirst block of the EDID. In that case we will call\nconnector_bad_edid() without having re-allocated memory based on\n`edid[0x7e]`.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2021-47444"
                }
            ]
        }
    ]
}