{
    "type": "bundle",
    "id": "bundle--a7c699be-7063-4956-97f3-b3373fba5367",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c3214c8f-2e4c-486f-b1ef-1835f9610fe3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-31T01:57:53.733952Z",
            "modified": "2025-03-31T01:57:53.733952Z",
            "name": "CVE-2025-2953",
            "description": "A vulnerability, which was classified as problematic, has been found in PyTorch 2.6.0+cu124. Affected by this issue is the function torch.mkldnn_max_pool2d. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-2953"
                }
            ]
        }
    ]
}