{
    "type": "bundle",
    "id": "bundle--4484d975-57b4-4691-9936-9995046cb1bc",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--5a1dc519-a76d-4a5d-8aa9-295fc8c231a6",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-09-17T01:18:05.635576Z",
            "modified": "2024-09-17T01:18:05.635576Z",
            "name": "CVE-2024-44183",
            "description": "A logic error was addressed with improved error handling. This issue is fixed in macOS Ventura 13.7, iOS 17.7 and iPadOS 17.7, visionOS 2, watchOS 11, macOS Sequoia 15, iOS 18 and iPadOS 18, macOS Sonoma 14.7, tvOS 18. An app may be able to cause a denial-of-service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-44183"
                }
            ]
        }
    ]
}